export const SET_LOADING = 'SET_LOADING';
export const GET_TWEETS = 'GET_TWEETS';
export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS';
export const GET_TWEETS_ERROR = 'GET_TWEETS_ERROR';

export const GET_USER_SESSION = 'GET_USER_SESSION';
export const GET_USER_SESSION_SUCCESS = 'GET_USER_SESSION_SUCCESS';
export const GET_USER_SESSION_ERROR = 'GET_USER_SESSION_ERROR';
export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_SEARCH_FORM = 'UPDATE_SEARCH_FORM';
export const CLEAR_SEARCH_FORM = 'CLEAR_SEARCH_FORM';
